import "../Style/Header.scss";
import "../Style/Footer.scss";
import "../Style/Featured.scss";
import "../Style/Hero.scss";
import "../Style/icomoon.css";
import "../Style/Button.scss";
import "../Style/top3.scss";
import "bootstrap/dist/css/bootstrap.min.css";

import Header from "@/Components/Header";
import Footer from "@/Components/Footer";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "../Style/Products.scss";
import "../Style/About.scss";
import "../Style/Counter.scss";

import "./globals.css";
export const metadata = {
  title: "Bs Surgical Suppliers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css?family=Material+Icons%7CMaterial+Icons+Outlined%7CMaterial+Icons+Two+Tone%7CMaterial+Icons+Round%7CMaterial+Icons+Sharp"
          rel="stylesheet"
        />
      </head>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
